name: CI pipeline

on:
  pull_request:
    branches: main

jobs:
  Tests:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "💡The ${{github.repository}} repository has been cloned to the runner"
      - run: echo "The runner is now ready to test your code with pytest"

      - name: Set up python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest
